# Generated by Django 6.0 on 2025-12-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_payment_aid_alter_payment_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='aid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cid',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
