# Generated by Django 6.0 on 2025-12-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_payment_aid_alter_payment_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
