# Generated by Django 6.0 on 2025-12-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_payment_approved_at_alter_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
