# Generated by Django 6.0 on 2025-12-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_board_likes'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes_member', to='member.member'),
        ),
    ]
