# Generated by Django 6.0 on 2025-12-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
