# Generated by Django 6.0 on 2025-12-26 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
