# Generated by SafeMap template
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('happened_at', models.DateTimeField()),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('traffic', '교통사고'), ('violence', '폭력/위협'), ('fire', '화재/연기'), ('lost', '분실/도난'), ('etc', '기타')], default='etc', max_length=20)),
                ('risk', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
