# Generated by ChatGPT
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='sido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='sigungu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='dong',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
