# Generated by ChatGPT
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('received', '접수됨'), ('processing', '처리중'), ('done', '완료')], default='received', max_length=20),
        ),
    ]
